services:
  - type: web
    name: genome-web
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=3 --preload
    preDeployCommand: python migrate.py
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: genome-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: genome-redis
          type: keyvalue
          property: connectionString
      - key: SPOTIPY_CLIENT_ID
        sync: false
      - key: SPOTIPY_CLIENT_SECRET
        sync: false
      - key: SPOTIPY_REDIRECT_URI
        sync: false
      - key: SECRET_KEY
        sync: false

  - type: worker
    name: genome-worker
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements-worker.txt
    startCommand: python worker.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: genome-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: genome-redis
          type: keyvalue
          property: connectionString
      - key: SPOTIPY_CLIENT_ID
        sync: false
      - key: SPOTIPY_CLIENT_SECRET
        sync: false
      - key: SPOTIPY_REDIRECT_URI
        sync: false
      - key: SECRET_KEY
        sync: false

  - type: keyvalue
    name: genome-redis
    plan: free                # or omit to use the default tier for Key Value
    ipAllowList: []           # internal-only access
    maxmemoryPolicy: allkeys-lru

databases:
  - name: genome-db
    postgresMajorVersion: "17"
    plan: basic-1gb           # <- modern Postgres plan (use 'free' if you want)
    databaseName: genome
    user: genome
    ipAllowList: []           # internal-only access
